tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "on-tertiary-fixed": "#241a00",
                "tertiary": "#765b00",
                "on-error": "#ffffff",
                "surface-container-lowest": "#ffffff",
                "surface-container-highest": "#e6e0e9",
                "on-surface": "#1d1b20",
                "primary-fixed-dim": "#cfbcff",
                "tertiary-fixed-dim": "#e7c365",
                "primary": "#4f378a",
                "surface-dim": "#ded8e0",
                "outline": "#7a7582",
                "error-container": "#ffdad6",
                "error": "#ba1a1a",
                "on-primary": "#ffffff",
                "on-secondary-fixed": "#1f1635",
                "on-primary-fixed-variant": "#4f378a",
                "on-secondary-fixed-variant": "#4b4263",
                "on-tertiary": "#ffffff",
                "on-error-container": "#93000a",
                "primary-fixed": "#e9ddff",
                "inverse-primary": "#cfbcff",
                "secondary": "#63597c",
                "on-secondary-container": "#645a7d",
                "background": "#fdf7ff",
                "tertiary-container": "#c9a74d",
                "secondary-fixed": "#e9ddff",
                "inverse-surface": "#322f35",
                "surface-tint": "#6750a4",
                "on-primary-fixed": "#22005d",
                "outline-variant": "#cbc4d2",
                "tertiary-fixed": "#ffdf93",
                "surface-bright": "#fdf7ff",
                "on-tertiary-fixed-variant": "#594400",
                "inverse-on-surface": "#f5eff7",
                "surface-variant": "#e6e0e9",
                "on-primary-container": "#e0d2ff",
                "secondary-container": "#e1d4fd",
                "surface": "#fdf7ff",
                "surface-container-low": "#f8f2fa",
                "surface-container-high": "#ece6ee",
                "on-tertiary-container": "#503d00",
                "on-secondary": "#ffffff",
                "on-surface-variant": "#494551",
                "surface-container": "#f2ecf4",
                "secondary-fixed-dim": "#cdc0e9",
                "primary-container": "#6750a4",
                "on-background": "#1d1b20",
                "bauhaus-red": "#D02020",
                "bauhaus-blue": "#1040C0",
                "bauhaus-yellow": "#F0C020"
            },
            "borderRadius": {
                "DEFAULT": "0px",
                "lg": "0px",
                "xl": "0px",
                "full": "9999px"
            },
            "spacing": {
                "margin-mobile": "24px",
                "unit": "8px",
                "gutter": "32px",
                "divider-weight": "4px",
                "margin-desktop": "64px"
            },
            "fontFamily": {
                "label-mono": ["Outfit"],
                "display-mobile": ["Outfit"],
                "section-heading": ["Outfit"],
                "display": ["Outfit"],
                "body-md": ["Outfit"],
                "body-lg": ["Outfit"]
            },
            "fontSize": {
                "label-mono": ["14px", {"lineHeight": "1.0", "letterSpacing": "0.1em", "fontWeight": "700"}],
                "display-mobile": ["48px", {"lineHeight": "1.0", "letterSpacing": "-0.05em", "fontWeight": "900"}],
                "section-heading": ["32px", {"lineHeight": "1.2", "letterSpacing": "0.02em", "fontWeight": "900"}],
                "display": ["84px", {"lineHeight": "1.0", "letterSpacing": "-0.05em", "fontWeight": "900"}],
                "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
                "body-lg": ["20px", {"lineHeight": "1.6", "fontWeight": "400"}]
            }
        },
    },
}
